/* eslint-disable sort-keys */
// Prettier options
module.exports = {
	printWidth                : 80,
	tabWidth                  : 2,
	useTabs                   : false,
	semi                      : true,
	singleQuote               : false,
	quoteProps                : 'as-needed',
	jsxSingleQuote            : false,
	trailingCommas            : 'es5',
	bracketSameLine           : false,
	bracketSpacing            : true,
	arrowParens               : 'always',
	rangeStart                : 0,
	rangeEnd                  : Infinity,
	parser                    : undefined,
	filePath                  : undefined,
	requirePragma             : false,
	insertPragma              : false,
	proseWrap                 : 'preserve',
	htmlWhitespaceSensitivity : 'css',
	vueIndentScriptAndStyle   : false,
	endOfLine                 : 'lf',
	embeddedLanguageFormatting: 'auto',
	singleAttributePerLine    : true,
};